name: Simple Cron Test

on:
  schedule:
    - cron: '*/30 * * * *'  # รันทุก 5 นาที
  workflow_dispatch:

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch@2 xml2js

      - name: Run script to update index.html
        run: |
          node <<'EOF'
          const fetch = require('node-fetch');
          const { parseStringPromise } = require('xml2js');

          const loginUrl = 'https://cloud.ufxtv.com/api/user/login/?user_email=BE0268&user_password=1111&kauth=';
          const playBaseUrl = 'https://cloud.ufxtv.com/api/tv/channels/play/?c=uflix-epl1&kauth=';

          async function getPlaylist(user_loggedsession) {
                  const playUrl = `${playBaseUrl}&user_loggedsession=${user_loggedsession}`;
                  const response = await fetch(playUrl);
                  const text = await response.text();
                  return text.includes('<clear_url>') ? text : null;
              }
          
              // ดึง session ใหม่
              async function login() {
                  const response = await fetch(loginUrl);
                  const text = await response.text();
                  const sessionMatch = text.match(/<user_loggedsession>(.*?)<\/user_loggedsession>/);
                  return sessionMatch ? sessionMatch[1] : null;
              }
          
              // ดึง clear_url จาก response XML
              function extractClearUrl(xml) {
                  const match = xml.match(/<clear_url>(.*?)<\/clear_url>/);
                  return match ? match[1] : null;
              }

              (async function() {
                const session = await login();
                if (session) {
                    const xmlData = await getPlaylist(session);
                    const clearUrl = extractClearUrl(xmlData);
                    if (clearUrl) {
                        renderPlaylist(clearUrl);
                    } else {
                        console.error("ไม่พบ clear_url ในข้อมูลที่ได้รับ");
                    }
                } else {
                    console.error("ไม่สามารถเข้าสู่ระบบได้");
                }
          
              // แสดงผลลัพธ์แบบ playlist
              function renderPlaylist(clearUrl) {
                  const fixedUrl = clearUrl.replace('playlist.m3u8', 'chunks.m3u8');
                  const output = `
              <!DOCTYPE html>
              <html lang="th">
              <head>
              <meta charset="UTF-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1.0">
                  <title>playlist</title>
              	</head>
              	
                  <style>
                      .hidden-link {
                          display: none;
                          }
                      .invisible-link {
                          visibility: hidden;
                      }
               </style>
              <style>.hiddenx-link {
              
              #EXTM3U 
              
              ########################################
              ช่องกีฬาทั่วไป
              ########################################
              
              #EXTINF:-1 group-title="ช่องกีฬาทั่วไป" tvg-logo="https://rentapi.blackboxsys.net/images/png/epl-1.png",EPL 01
              #EXTVLCOPT:http-referrer=https://99dooball.com/
              https://cdn2.aws-live-streaming.com/lsmscore/epl1_sd/chunks.m3u8
              
              #EXTINF:-1 group-title="ช่องกีฬาทั่วไป" tvg-logo="https://rentapi.blackboxsys.net/images/png/epl-1.png",EPL 02
              #EXTVLCOPT:http-referrer=https://cloud.ufxtv.com/
              #EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
              #EXTVLCOPT:http-origin=https://cloud.ufxtv.com
              #EXTVLCOPT:http-accept=*/*
              #EXTVLCOPT:http-accept-encoding=gzip, deflate, br, zstd
              #EXTVLCOPT:http-accept-language=en-US,en;q=0.9,th;q=0.8
              ${fixedUrl}
              
              
              }</style>
              
              <body bgcolor="FFFFFF">
              
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              </body>
              </html>
              `;
              require('fs').writeFileSync('index.html', output);
              console.log("✅ Updated index.html with clear_url");
          })();
          EOF

      - name: Commit and Push
        run: |
          git config --global user.name "devjob4475"
          git config --global user.email "thananchai216@gmail.com"
          git add index.html
          git commit -m "Auto update HTML on $(TZ='Asia/Bangkok' date)" || echo "No changes to commit"
          git push
