name: Open Google Link

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  open-link:
    runs-on: ubuntu-latest
    
    steps:
      - name: Open Google Link
        run: curl https://www.google.com
