name: Simple Cron Test

on:
  schedule:
    - cron:  '*/15 * * * *'    # At every 15th minute
  workflow_dispatch:

jobs:
  print-time:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The time is $(date -u)"
