name: Open and Show Website Output

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  open-link:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch and Display Website Output
        run: |
          echo "Fetching https://devjob4475.github.io/pornbox.html ..."
          curl -L https://devjob4475.github.io/pornbox.html
